name: Build and publish docker images

on:
  push:
    branches:
      - "main"

jobs:
  build-and-publish:
    runs-on: build-runner
    container: gitea/runner-images:ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: "${{ vars.DOCKER_DEFAULT_REGISTRY_URI }}"
          username: "${{ secrets.DOCKER_DEFAULT_REGISTRY_USERNAME }}"
          password: "${{ secrets.DOCKER_DEFAULT_REGISTRY_PASSWORD }}"

      - name: Extract tag name
        shell: bash
        run: |
          echo "$GITHUB_REF_NAME"

          pattern="(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?"

          version=$(echo "$GITHUB_REF_NAME" | grep -oP "$pattern" || echo "" )

          if [ -n "$version" ]; then
            echo "has version"
            echo "tag=$version" >> $GITHUB_OUTPUT
          else
            echo "has no version"
            echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi
        id: extract_tag

      - name: Build and push API Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Stross.API/Dockerfile
          push: true
          tags: "${{ vars.DOCKER_API_REPOSITORY }}:${{ steps.extract_tag.outputs.tag }}"

      - name: Build and push downloader YT Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Stross.Downloader.YT/Dockerfile
          push: true
          tags: "${{ vars.DOCKER_DOWNLOADER_YT_REPOSITORY }}:${{ steps.extract_tag.outputs.tag }}"

      - name: Build and push downloader SoundCloud Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Stross.Downloader.SoundCloud/Dockerfile
          push: true
          tags: "${{ vars.DOCKER_DOWNLOADER_SOUNDCLOUD_REPOSITORY }}:${{ steps.extract_tag.outputs.tag }}"

      - name: Get ssh host key for gitea
        if: github.ref == 'refs/heads/main'
        shell: bash
        run: |
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts && touch ~/.ssh/id_ed25519
          ssh-keyscan -p 6022 ${{ vars.GIT_INSTANCE_URL }} > ~/.ssh/known_hosts
          echo "${{ secrets.SSH_KEY_GITEA }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Update deployment repository
        if: github.ref == 'refs/heads/main'
        shell: bash
        run: |
          git clone "${{ vars.DEPLOYMENT_REPO_URL }}" deployment-repo
          cd deployment-repo

          # Configure git
          git config user.name "gitea"
          git config user.email "${{ vars.GIT_EMAIL }}"

          # Search and replace the image tag with the new tag
          find . -name "*stross_dev-compose.yaml" -exec sed -i 's|${{ vars.COMPOSE_DOWNLOADER_YT_REPLACE_REGEX }}${{ steps.extract_tag.outputs.tag }}|g' {} +
          find . -name "*stross_dev-compose.yaml" -exec sed -i 's|${{ vars.COMPOSE_DOWNLOADER_SOUNDCLOUD_REPLACE_REGEX }}${{ steps.extract_tag.outputs.tag }}|g' {} +
          find . -name "*stross_dev-compose.yaml" -exec sed -i 's|${{ vars.COMPOSE_API_REPLACE_REGEX }}${{ steps.extract_tag.outputs.tag }}|g' {} +

          # Commit and push changes
          git add .
          git commit -m "feat(stross): Update image tag to ${{ steps.extract_tag.outputs.tag }}" || echo "No changes to commit"
          git push

      - name: Send webhook notification
        if: github.ref == 'refs/heads/main'
        shell: bash
        run: |
          curl -k -X POST "${{ secrets.WEBHOOK_URL }}"