name: Build and publish docker images

on:
  push:
    branches:
      - "main"

jobs:
  build-and-publish:
    runs-on: build-runner
    container: gitea/runner-images:ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: "${{ vars.DOCKER_DEFAULT_REGISTRY_URI }}"
          username: "${{ secrets.DOCKER_DEFAULT_REGISTRY_USERNAME }}"
          password: "${{ secrets.DOCKER_DEFAULT_REGISTRY_PASSWORD }}"

      - name: Build and push API Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Stross.API/Dockerfile
          push: true
          tags: "${{ vars.DOCKER_API_REPOSITORY }}:dev"

      - name: Build and push downloader yt Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Stross.Downloader.YT/Dockerfile
          push: true
          tags: "${{ vars.DOCKER_DOWNLOADER_YT_REPOSITORY }}:dev"
