<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Stross.Domain\Stross.Domain.csproj"/>
        <ProjectReference Include="..\Stross.Exception\Stross.Exception.csproj"/>
        <ProjectReference Include="..\Stross.Infrastructure\Stross.Infrastructure.csproj"/>
        <ProjectReference Include="..\Stross.SubsonicModels\Stross.SubsonicModels.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1"/>
        <PackageReference Include="MediatR" Version="12.5.0"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2"/>
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.2"/>
    </ItemGroup>

</Project>
