//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console https://www.subsonic.org/pages/inc/api/schema/subsonic-rest-api-1.16.1.xsd -o /home/brent/Data/git/private/stross/backend/ --sf --csm Init -n Stross.SubsonicModels --ct System.Collections.Generic.List`1
namespace Stross.SubsonicModels
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ArtistsID3", Namespace="http://subsonic.org/restapi")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ArtistsId3
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Text.Json.Serialization.JsonIgnore]
        private System.Collections.Generic.List<IndexId3> _index;
        
        [System.Xml.Serialization.XmlElementAttribute("index")]
        public System.Collections.Generic.List<IndexId3> Index
        {
            get
            {
                return _index;
            }
            init
            {
                _index = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Index collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Text.Json.Serialization.JsonIgnore]
        public bool IndexSpecified
        {
            get
            {
                return ((this.Index != null) 
                            && (this.Index.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ArtistsId3" /> class.</para>
        /// </summary>
        public ArtistsId3()
        {
            this._index = new System.Collections.Generic.List<IndexId3>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("ignoredArticles")]
        public string IgnoredArticles { get; set; }
    }
}
