//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console https://www.subsonic.org/pages/inc/api/schema/subsonic-rest-api-1.16.1.xsd -o /home/brent/Data/git/private/stross/backend/ --sf --csm Init -n Stross.SubsonicModels --ct System.Collections.Generic.List`1
namespace Stross.SubsonicModels
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Child", Namespace="http://subsonic.org/restapi")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NowPlayingEntry))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PodcastEpisode))]
    public partial class Child
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("id")]
        public string Id { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("parent")]
        public string Parent { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("isDir")]
        public bool IsDir { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("title")]
        public string Title { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("album")]
        public string Album { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("artist")]
        public string Artist { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("track")]
        public int Track { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("year")]
        public int Year { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("genre")]
        public string Genre { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("coverArt")]
        public string CoverArt { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("size")]
        public long Size { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("contentType")]
        public string ContentType { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("suffix")]
        public string Suffix { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("transcodedContentType")]
        public string TranscodedContentType { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("transcodedSuffix")]
        public string TranscodedSuffix { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("duration")]
        public int Duration { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("bitRate")]
        public int BitRate { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("path")]
        public string Path { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("isVideo")]
        public bool IsVideo { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 5.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(int), "1", "5")]
        [System.Xml.Serialization.XmlAttributeAttribute("userRating")]
        public int UserRating { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1.0.</para>
        /// <para xml:lang="en">Maximum inclusive value: 5.0.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(double), "1.0", "5.0")]
        [System.Xml.Serialization.XmlAttributeAttribute("averageRating")]
        public double AverageRating { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("playCount")]
        public long PlayCount { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("discNumber")]
        public int DiscNumber { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("created", DataType="dateTime")]
        public System.DateTime Created { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("starred", DataType="dateTime")]
        public System.DateTime Starred { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("albumId")]
        public string AlbumId { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("artistId")]
        public string ArtistId { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public MediaType Type { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("bookmarkPosition")]
        public long BookmarkPosition { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("originalWidth")]
        public int OriginalWidth { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("originalHeight")]
        public int OriginalHeight { get; set; }
    }
}
