//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console https://www.subsonic.org/pages/inc/api/schema/subsonic-rest-api-1.16.1.xsd -o /home/brent/Data/git/private/stross/backend/ --sf --csm Init -n Stross.SubsonicModels --ct System.Collections.Generic.List`1
namespace Stross.SubsonicModels
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Directory", Namespace="http://subsonic.org/restapi")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Directory
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Text.Json.Serialization.JsonIgnore]
        private System.Collections.Generic.List<Child> _child;
        
        [System.Xml.Serialization.XmlElementAttribute("child")]
        public System.Collections.Generic.List<Child> Child
        {
            get
            {
                return _child;
            }
            init
            {
                _child = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Child collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Text.Json.Serialization.JsonIgnore]
        public bool ChildSpecified
        {
            get
            {
                return ((this.Child != null) 
                            && (this.Child.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Directory" /> class.</para>
        /// </summary>
        public Directory()
        {
            this._child = new System.Collections.Generic.List<Child>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("id")]
        public string Id { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("parent")]
        public string Parent { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("starred", DataType="dateTime")]
        public System.DateTime Starred { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Starred property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Text.Json.Serialization.JsonIgnore]
        public bool StarredSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 5.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(int), "1", "5")]
        [System.Xml.Serialization.XmlAttributeAttribute("userRating")]
        public int UserRating { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the UserRating property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Text.Json.Serialization.JsonIgnore]
        public bool UserRatingSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1.0.</para>
        /// <para xml:lang="en">Maximum inclusive value: 5.0.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(double), "1.0", "5.0")]
        [System.Xml.Serialization.XmlAttributeAttribute("averageRating")]
        public double AverageRating { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the AverageRating property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Text.Json.Serialization.JsonIgnore]
        public bool AverageRatingSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("playCount")]
        public long PlayCount { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the PlayCount property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Text.Json.Serialization.JsonIgnore]
        public bool PlayCountSpecified { get; set; }
    }
}
