//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console https://www.subsonic.org/pages/inc/api/schema/subsonic-rest-api-1.16.1.xsd -o /home/brent/Data/git/private/stross/backend/ --sf --csm Init -n Stross.SubsonicModels --ct System.Collections.Generic.List`1
namespace Stross.SubsonicModels
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Indexes", Namespace="http://subsonic.org/restapi")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Indexes
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Artist> _shortcut;
        
        [System.Xml.Serialization.XmlElementAttribute("shortcut")]
        public System.Collections.Generic.List<Artist> Shortcut
        {
            get
            {
                return _shortcut;
            }
            init
            {
                _shortcut = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Shortcut collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShortcutSpecified
        {
            get
            {
                return ((this.Shortcut != null) 
                            && (this.Shortcut.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Indexes" /> class.</para>
        /// </summary>
        public Indexes()
        {
            this._shortcut = new System.Collections.Generic.List<Artist>();
            this._index = new System.Collections.Generic.List<Index>();
            this._child = new System.Collections.Generic.List<Child>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Index> _index;
        
        [System.Xml.Serialization.XmlElementAttribute("index")]
        public System.Collections.Generic.List<Index> Index
        {
            get
            {
                return _index;
            }
            init
            {
                _index = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Index collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndexSpecified
        {
            get
            {
                return ((this.Index != null) 
                            && (this.Index.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Child> _child;
        
        [System.Xml.Serialization.XmlElementAttribute("child")]
        public System.Collections.Generic.List<Child> Child
        {
            get
            {
                return _child;
            }
            init
            {
                _child = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Child collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChildSpecified
        {
            get
            {
                return ((this.Child != null) 
                            && (this.Child.Count != 0));
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("lastModified")]
        public long LastModified { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("ignoredArticles")]
        public string IgnoredArticles { get; set; }
    }
}
