//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console https://www.subsonic.org/pages/inc/api/schema/subsonic-rest-api-1.16.1.xsd -o /home/brent/Data/git/private/stross/backend/ --sf --csm Init -n Stross.SubsonicModels --ct System.Collections.Generic.List`1

using System.Text.Json.Serialization;
using Stross.SubsonicModels.JsonConverters;

namespace Stross.SubsonicModels
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Lyrics", Namespace="http://subsonic.org/restapi")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Lyrics
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("artist")]
        public string Artist { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("title")]
        public string Title { get; set; }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        [JsonConverter(typeof(StringArrayToValueJsonConverter))]
        [JsonPropertyName("value")]
        public string[] Text { get; set; }
    }
}
