//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console https://www.subsonic.org/pages/inc/api/schema/subsonic-rest-api-1.16.1.xsd -o /home/brent/Data/git/private/stross/backend/ --sf --csm Init -n Stross.SubsonicModels --ct System.Collections.Generic.List`1
namespace Stross.SubsonicModels
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MediaType", Namespace="http://subsonic.org/restapi")]
    public enum MediaType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("music")]
        Music,
        
        [System.Xml.Serialization.XmlEnumAttribute("podcast")]
        Podcast,
        
        [System.Xml.Serialization.XmlEnumAttribute("audiobook")]
        Audiobook,
        
        [System.Xml.Serialization.XmlEnumAttribute("video")]
        Video,
    }
}
