//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console https://www.subsonic.org/pages/inc/api/schema/subsonic-rest-api-1.16.1.xsd -o /home/brent/Data/git/private/stross/backend/ --sf --csm Init -n Stross.SubsonicModels --ct System.Collections.Generic.List`1
namespace Stross.SubsonicModels
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PlayQueue", Namespace="http://subsonic.org/restapi")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PlayQueue
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Text.Json.Serialization.JsonIgnore]
        private System.Collections.Generic.List<Child> _entry;
        
        [System.Xml.Serialization.XmlElementAttribute("entry")]
        public System.Collections.Generic.List<Child> Entry
        {
            get
            {
                return _entry;
            }
            init
            {
                _entry = value;
            }
        }
        
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PlayQueue" /> class.</para>
        /// </summary>
        public PlayQueue()
        {
            this._entry = new System.Collections.Generic.List<Child>();
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("current")]
        public int Current { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("position")]
        public long Position { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("username")]
        public string Username { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("changed", DataType="dateTime")]
        public System.DateTime Changed { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("changedBy")]
        public string ChangedBy { get; set; }
    }
}
