//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console https://www.subsonic.org/pages/inc/api/schema/subsonic-rest-api-1.16.1.xsd -o /home/brent/Data/git/private/stross/backend/ --sf --csm Init -n Stross.SubsonicModels --ct System.Collections.Generic.List`1
namespace Stross.SubsonicModels
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PodcastEpisode", Namespace="http://subsonic.org/restapi")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PodcastEpisode : Child
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("streamId")]
        public string StreamId { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("channelId")]
        public string ChannelId { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("description")]
        public string Description { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("status")]
        public PodcastStatus Status { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("publishDate", DataType="dateTime")]
        public System.DateTime PublishDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the PublishDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PublishDateSpecified { get; set; }
    }
}
