//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console https://www.subsonic.org/pages/inc/api/schema/subsonic-rest-api-1.16.1.xsd -o /home/brent/Data/git/private/stross/backend/ --sf --csm Init -n Stross.SubsonicModels --ct System.Collections.Generic.List`1
namespace Stross.SubsonicModels
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Response", Namespace="http://subsonic.org/restapi")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("subsonic-response", Namespace="http://subsonic.org/restapi")]
    public partial class Response
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MusicFolder> _musicFolders;
        
        [System.Xml.Serialization.XmlArrayAttribute("musicFolders")]
        [System.Xml.Serialization.XmlArrayItemAttribute("musicFolder", Namespace="http://subsonic.org/restapi")]
        public System.Collections.Generic.List<MusicFolder> MusicFolders
        {
            get
            {
                return _musicFolders;
            }
            init
            {
                _musicFolders = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the MusicFolders collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MusicFoldersSpecified
        {
            get
            {
                return ((this.MusicFolders != null) 
                            && (this.MusicFolders.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Response" /> class.</para>
        /// </summary>
        public Response()
        {
            this._musicFolders = new System.Collections.Generic.List<MusicFolder>();
            this._genres = new System.Collections.Generic.List<Genre>();
            this._videos = new System.Collections.Generic.List<Child>();
            this._nowPlaying = new System.Collections.Generic.List<NowPlayingEntry>();
            this._playlists = new System.Collections.Generic.List<Playlist>();
            this._users = new System.Collections.Generic.List<User>();
            this._chatMessages = new System.Collections.Generic.List<ChatMessage>();
            this._albumList = new System.Collections.Generic.List<Child>();
            this._albumList2 = new System.Collections.Generic.List<AlbumId3>();
            this._randomSongs = new System.Collections.Generic.List<Child>();
            this._songsByGenre = new System.Collections.Generic.List<Child>();
            this._podcasts = new System.Collections.Generic.List<PodcastChannel>();
            this._newestPodcasts = new System.Collections.Generic.List<PodcastEpisode>();
            this._internetRadioStations = new System.Collections.Generic.List<InternetRadioStation>();
            this._bookmarks = new System.Collections.Generic.List<Bookmark>();
            this._shares = new System.Collections.Generic.List<Share>();
            this._similarSongs = new System.Collections.Generic.List<Child>();
            this._similarSongs2 = new System.Collections.Generic.List<Child>();
            this._topSongs = new System.Collections.Generic.List<Child>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("indexes")]
        public Indexes Indexes { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("directory")]
        public Directory Directory { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Genre> _genres;
        
        [System.Xml.Serialization.XmlArrayAttribute("genres")]
        [System.Xml.Serialization.XmlArrayItemAttribute("genre", Namespace="http://subsonic.org/restapi")]
        public System.Collections.Generic.List<Genre> Genres
        {
            get
            {
                return _genres;
            }
            init
            {
                _genres = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Genres collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GenresSpecified
        {
            get
            {
                return ((this.Genres != null) 
                            && (this.Genres.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("artists")]
        public ArtistsId3 Artists { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("artist")]
        public ArtistWithAlbumsId3 Artist { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("album")]
        public AlbumWithSongsId3 Album { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("song")]
        public Child Song { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Child> _videos;
        
        [System.Xml.Serialization.XmlArrayAttribute("videos")]
        [System.Xml.Serialization.XmlArrayItemAttribute("video", Namespace="http://subsonic.org/restapi")]
        public System.Collections.Generic.List<Child> Videos
        {
            get
            {
                return _videos;
            }
            init
            {
                _videos = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Videos collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VideosSpecified
        {
            get
            {
                return ((this.Videos != null) 
                            && (this.Videos.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("videoInfo")]
        public VideoInfo VideoInfo { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<NowPlayingEntry> _nowPlaying;
        
        [System.Xml.Serialization.XmlArrayAttribute("nowPlaying")]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Namespace="http://subsonic.org/restapi")]
        public System.Collections.Generic.List<NowPlayingEntry> NowPlaying
        {
            get
            {
                return _nowPlaying;
            }
            init
            {
                _nowPlaying = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the NowPlaying collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NowPlayingSpecified
        {
            get
            {
                return ((this.NowPlaying != null) 
                            && (this.NowPlaying.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("searchResult")]
        public SearchResult SearchResult { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("searchResult2")]
        public SearchResult2 SearchResult2 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("searchResult3")]
        public SearchResult3 SearchResult3 { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Playlist> _playlists;
        
        [System.Xml.Serialization.XmlArrayAttribute("playlists")]
        [System.Xml.Serialization.XmlArrayItemAttribute("playlist", Namespace="http://subsonic.org/restapi")]
        public System.Collections.Generic.List<Playlist> Playlists
        {
            get
            {
                return _playlists;
            }
            init
            {
                _playlists = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Playlists collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlaylistsSpecified
        {
            get
            {
                return ((this.Playlists != null) 
                            && (this.Playlists.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("playlist")]
        public PlaylistWithSongs Playlist { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("jukeboxStatus")]
        public JukeboxStatus JukeboxStatus { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("jukeboxPlaylist")]
        public JukeboxPlaylist JukeboxPlaylist { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("license")]
        public License License { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<User> _users;
        
        [System.Xml.Serialization.XmlArrayAttribute("users")]
        [System.Xml.Serialization.XmlArrayItemAttribute("user", Namespace="http://subsonic.org/restapi")]
        public System.Collections.Generic.List<User> Users
        {
            get
            {
                return _users;
            }
            init
            {
                _users = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Users collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UsersSpecified
        {
            get
            {
                return ((this.Users != null) 
                            && (this.Users.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("user")]
        public User User { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ChatMessage> _chatMessages;
        
        [System.Xml.Serialization.XmlArrayAttribute("chatMessages")]
        [System.Xml.Serialization.XmlArrayItemAttribute("chatMessage", Namespace="http://subsonic.org/restapi")]
        public System.Collections.Generic.List<ChatMessage> ChatMessages
        {
            get
            {
                return _chatMessages;
            }
            init
            {
                _chatMessages = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ChatMessages collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChatMessagesSpecified
        {
            get
            {
                return ((this.ChatMessages != null) 
                            && (this.ChatMessages.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Child> _albumList;
        
        [System.Xml.Serialization.XmlArrayAttribute("albumList")]
        [System.Xml.Serialization.XmlArrayItemAttribute("album", Namespace="http://subsonic.org/restapi")]
        public System.Collections.Generic.List<Child> AlbumList
        {
            get
            {
                return _albumList;
            }
            init
            {
                _albumList = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AlbumList collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AlbumListSpecified
        {
            get
            {
                return ((this.AlbumList != null) 
                            && (this.AlbumList.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<AlbumId3> _albumList2;
        
        [System.Xml.Serialization.XmlArrayAttribute("albumList2")]
        [System.Xml.Serialization.XmlArrayItemAttribute("album", Namespace="http://subsonic.org/restapi")]
        public System.Collections.Generic.List<AlbumId3> AlbumList2
        {
            get
            {
                return _albumList2;
            }
            init
            {
                _albumList2 = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AlbumList2 collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AlbumList2Specified
        {
            get
            {
                return ((this.AlbumList2 != null) 
                            && (this.AlbumList2.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Child> _randomSongs;
        
        [System.Xml.Serialization.XmlArrayAttribute("randomSongs")]
        [System.Xml.Serialization.XmlArrayItemAttribute("song", Namespace="http://subsonic.org/restapi")]
        public System.Collections.Generic.List<Child> RandomSongs
        {
            get
            {
                return _randomSongs;
            }
            init
            {
                _randomSongs = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the RandomSongs collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RandomSongsSpecified
        {
            get
            {
                return ((this.RandomSongs != null) 
                            && (this.RandomSongs.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Child> _songsByGenre;
        
        [System.Xml.Serialization.XmlArrayAttribute("songsByGenre")]
        [System.Xml.Serialization.XmlArrayItemAttribute("song", Namespace="http://subsonic.org/restapi")]
        public System.Collections.Generic.List<Child> SongsByGenre
        {
            get
            {
                return _songsByGenre;
            }
            init
            {
                _songsByGenre = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the SongsByGenre collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SongsByGenreSpecified
        {
            get
            {
                return ((this.SongsByGenre != null) 
                            && (this.SongsByGenre.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("lyrics")]
        public Lyrics Lyrics { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<PodcastChannel> _podcasts;
        
        [System.Xml.Serialization.XmlArrayAttribute("podcasts")]
        [System.Xml.Serialization.XmlArrayItemAttribute("channel", Namespace="http://subsonic.org/restapi")]
        public System.Collections.Generic.List<PodcastChannel> Podcasts
        {
            get
            {
                return _podcasts;
            }
            init
            {
                _podcasts = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Podcasts collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PodcastsSpecified
        {
            get
            {
                return ((this.Podcasts != null) 
                            && (this.Podcasts.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<PodcastEpisode> _newestPodcasts;
        
        [System.Xml.Serialization.XmlArrayAttribute("newestPodcasts")]
        [System.Xml.Serialization.XmlArrayItemAttribute("episode", Namespace="http://subsonic.org/restapi")]
        public System.Collections.Generic.List<PodcastEpisode> NewestPodcasts
        {
            get
            {
                return _newestPodcasts;
            }
            init
            {
                _newestPodcasts = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the NewestPodcasts collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NewestPodcastsSpecified
        {
            get
            {
                return ((this.NewestPodcasts != null) 
                            && (this.NewestPodcasts.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<InternetRadioStation> _internetRadioStations;
        
        [System.Xml.Serialization.XmlArrayAttribute("internetRadioStations")]
        [System.Xml.Serialization.XmlArrayItemAttribute("internetRadioStation", Namespace="http://subsonic.org/restapi")]
        public System.Collections.Generic.List<InternetRadioStation> InternetRadioStations
        {
            get
            {
                return _internetRadioStations;
            }
            init
            {
                _internetRadioStations = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the InternetRadioStations collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InternetRadioStationsSpecified
        {
            get
            {
                return ((this.InternetRadioStations != null) 
                            && (this.InternetRadioStations.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Bookmark> _bookmarks;
        
        [System.Xml.Serialization.XmlArrayAttribute("bookmarks")]
        [System.Xml.Serialization.XmlArrayItemAttribute("bookmark", Namespace="http://subsonic.org/restapi")]
        public System.Collections.Generic.List<Bookmark> Bookmarks
        {
            get
            {
                return _bookmarks;
            }
            init
            {
                _bookmarks = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Bookmarks collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BookmarksSpecified
        {
            get
            {
                return ((this.Bookmarks != null) 
                            && (this.Bookmarks.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("playQueue")]
        public PlayQueue PlayQueue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Share> _shares;
        
        [System.Xml.Serialization.XmlArrayAttribute("shares")]
        [System.Xml.Serialization.XmlArrayItemAttribute("share", Namespace="http://subsonic.org/restapi")]
        public System.Collections.Generic.List<Share> Shares
        {
            get
            {
                return _shares;
            }
            init
            {
                _shares = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Shares collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SharesSpecified
        {
            get
            {
                return ((this.Shares != null) 
                            && (this.Shares.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("starred")]
        public Starred Starred { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("starred2")]
        public Starred2 Starred2 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("albumInfo")]
        public AlbumInfo AlbumInfo { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("artistInfo")]
        public ArtistInfo ArtistInfo { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("artistInfo2")]
        public ArtistInfo2 ArtistInfo2 { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Child> _similarSongs;
        
        [System.Xml.Serialization.XmlArrayAttribute("similarSongs")]
        [System.Xml.Serialization.XmlArrayItemAttribute("song", Namespace="http://subsonic.org/restapi")]
        public System.Collections.Generic.List<Child> SimilarSongs
        {
            get
            {
                return _similarSongs;
            }
            init
            {
                _similarSongs = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the SimilarSongs collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SimilarSongsSpecified
        {
            get
            {
                return ((this.SimilarSongs != null) 
                            && (this.SimilarSongs.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Child> _similarSongs2;
        
        [System.Xml.Serialization.XmlArrayAttribute("similarSongs2")]
        [System.Xml.Serialization.XmlArrayItemAttribute("song", Namespace="http://subsonic.org/restapi")]
        public System.Collections.Generic.List<Child> SimilarSongs2
        {
            get
            {
                return _similarSongs2;
            }
            init
            {
                _similarSongs2 = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the SimilarSongs2 collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SimilarSongs2Specified
        {
            get
            {
                return ((this.SimilarSongs2 != null) 
                            && (this.SimilarSongs2.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Child> _topSongs;
        
        [System.Xml.Serialization.XmlArrayAttribute("topSongs")]
        [System.Xml.Serialization.XmlArrayItemAttribute("song", Namespace="http://subsonic.org/restapi")]
        public System.Collections.Generic.List<Child> TopSongs
        {
            get
            {
                return _topSongs;
            }
            init
            {
                _topSongs = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the TopSongs collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TopSongsSpecified
        {
            get
            {
                return ((this.TopSongs != null) 
                            && (this.TopSongs.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("scanStatus")]
        public ScanStatus ScanStatus { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("error")]
        public Error Error { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("status")]
        public ResponseStatus Status { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: \d+\.\d+\.\d+.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d+\\.\\d+\\.\\d+")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("version")]
        public string Version { get; set; }
    }
}
