//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console https://www.subsonic.org/pages/inc/api/schema/subsonic-rest-api-1.16.1.xsd -o /home/brent/Data/git/private/stross/backend/ --sf --csm Init -n Stross.SubsonicModels --ct System.Collections.Generic.List`1
namespace Stross.SubsonicModels
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Shares", Namespace="http://subsonic.org/restapi")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Shares
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Text.Json.Serialization.JsonIgnore]
        private System.Collections.Generic.List<Share> _share;
        
        [System.Xml.Serialization.XmlElementAttribute("share")]
        public System.Collections.Generic.List<Share> Share
        {
            get
            {
                return _share;
            }
            init
            {
                _share = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Share collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Text.Json.Serialization.JsonIgnore]
        public bool ShareSpecified
        {
            get
            {
                return ((this.Share != null) 
                            && (this.Share.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Shares" /> class.</para>
        /// </summary>
        public Shares()
        {
            this._share = new System.Collections.Generic.List<Share>();
        }
    }
}
