//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console https://www.subsonic.org/pages/inc/api/schema/subsonic-rest-api-1.16.1.xsd -o /home/brent/Data/git/private/stross/backend/ --sf --csm Init -n Stross.SubsonicModels --ct System.Collections.Generic.List`1
namespace Stross.SubsonicModels
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VideoInfo", Namespace="http://subsonic.org/restapi")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VideoInfo
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Text.Json.Serialization.JsonIgnore]
        private System.Collections.Generic.List<Captions> _captions;
        
        [System.Xml.Serialization.XmlElementAttribute("captions")]
        public System.Collections.Generic.List<Captions> Captions
        {
            get
            {
                return _captions;
            }
            init
            {
                _captions = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Captions collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Text.Json.Serialization.JsonIgnore]
        public bool CaptionsSpecified
        {
            get
            {
                return ((this.Captions != null) 
                            && (this.Captions.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="VideoInfo" /> class.</para>
        /// </summary>
        public VideoInfo()
        {
            this._captions = new System.Collections.Generic.List<Captions>();
            this._audioTrack = new System.Collections.Generic.List<AudioTrack>();
            this._conversion = new System.Collections.Generic.List<VideoConversion>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Text.Json.Serialization.JsonIgnore]
        private System.Collections.Generic.List<AudioTrack> _audioTrack;
        
        [System.Xml.Serialization.XmlElementAttribute("audioTrack")]
        public System.Collections.Generic.List<AudioTrack> AudioTrack
        {
            get
            {
                return _audioTrack;
            }
            init
            {
                _audioTrack = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AudioTrack collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Text.Json.Serialization.JsonIgnore]
        public bool AudioTrackSpecified
        {
            get
            {
                return ((this.AudioTrack != null) 
                            && (this.AudioTrack.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Text.Json.Serialization.JsonIgnore]
        private System.Collections.Generic.List<VideoConversion> _conversion;
        
        [System.Xml.Serialization.XmlElementAttribute("conversion")]
        public System.Collections.Generic.List<VideoConversion> Conversion
        {
            get
            {
                return _conversion;
            }
            init
            {
                _conversion = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Conversion collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Text.Json.Serialization.JsonIgnore]
        public bool ConversionSpecified
        {
            get
            {
                return ((this.Conversion != null) 
                            && (this.Conversion.Count != 0));
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("id")]
        public string Id { get; set; }
    }
}
