<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-Stross.Downloader.Soundcloud-3951b7f2-4b08-4732-9e57-670754f98ec2</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Grpc.AspNetCore" Version="2.76.0"/>
        <PackageReference Include="Grpc.AspNetCore.Web" Version="2.76.0"/>
        <PackageReference Include="Grpc.Core" Version="2.46.6"/>
        <PackageReference Include="Grpc.Net.Client.Web" Version="2.76.0"/>
        <PackageReference Include="NYoutubeDLP" Version="0.13.2"/>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Stross.Config\Stross.Config.csproj" />
      <ProjectReference Include="..\Stross.Proto\Stross.Proto.csproj" />
    </ItemGroup>
</Project>
